### ISSUE TITLE
Max Expiration date

### ISSUE THREAD

**Issue by geoherb** [aleripe/AnonymousId#4]
The max expiration date is about 12 days.

private const int MAXIMUM_COOKIE_TIMEOUT = 60 * 24 * 365 * 2;

Why that?  Is it a mistake? maybe you mean 2 years ( 60 * 60 * 24 * 365 * 2 )

Anyway, i need set expiration far more than 12 days

Is it possible?

**Comment by aleripe** [comment]
It's a mistake, a big one! It should have been two years... I'll fix it next week! Thanks for your feedback!

**Comment by geoherb** [comment]
thank you too, glad to help.

**Comment by aleripe** [comment]
Fixed in 396e7fbc0b08efa49673e103a39c67a04b5b6ba8
